---
- name: play para comprobar version mayor de 10
  hosts: all

  tasks:
    - name: version mayor o igual a 10
      ansible.builtin.debug:
        msg: " {{ansible_hostname}} es una version mayor o igual a 10, es la version {{ansible_distribution_version}}"
      when: ansible_distribution_version | int >= 10
